### ISSUE TITLE
Design System / Foundation / Grid Page

### ISSUE THREAD

**Issue by spania85** [startupjs/startupjs#112]
Here's the design for the foundation / Grid.
https://dm.invisionapp.com/share/56X3C43XA4K#/415773904_Grid
[data grid.txt](https://github.com/startupjs/startupjs/files/4555082/data.grid.txt)

**Comment by DaryaDecisionMapper** [comment]
Here is how we do mobile first currently: 
styles for mobile (by default)  —> tablet (from 768px) —> desktop (from 1024px) —> wide (from 1280px). The grids system has been discussed with Pavel Zhukov and it's not a trivial task to integrate it with flex boxes. It requires deep research, because we need to understand how to do it in a proper new way - doesn't make much sense to do it in the old way, because it's been decided to get rid of grids on IDG long time ago.
