### ISSUE TITLE
Design system / Foundation / Spacing

### ISSUE THREAD

**Issue by uxjavi** [startupjs/startupjs#113]
Here's the page for the spacing
https://dm.invisionapp.com/share/56X3C43XA4K#/415773905_Spacing
includes an explanation on how the feedback button works.
[spacing.txt](https://github.com/startupjs/startupjs/files/4555110/spacing.txt)
Link to sketch for teams, if you need an invite let me know.
https://www.sketch.com/s/69a22077-3c15-4dcb-bf20-57305b466a2d/p/echo-master-guide

**Comment by DaryaDecisionMapper** [comment]
There is a token name column here with the values $xs, $s, $m and so on - we're not planning to use them, because it's basically the same as gutters that we used to have before. It's not quite convenient and we have to keep in mind some things like how many units are in xxxl, for example, and then calculate how many pixels in these units. It's too much to keep in mind, that's why we use only units. 1 unit = 8 px

**Comment by uxjavi** [comment]
That content is old, I am going to close this as we should only refer to Figma. But to address the issue here: there are spacing rules that the design team is following and the devs should follow too, if they are not documented anywhere, how can they know what the rules are. **We should collaborate on this, not make it a dead-end where someone says no and the discussion ends there.**
